feat: Date, LineLike, NavigationMenu, PostCard, PostList, Title
DaniilBenyash/tms_blog pull request #3
Opened 2022-05-10 20:40 UTC by DaniilBenyash

2022-05-11 07:18 UTC, JohnyNiks requested changes

2022-05-11 07:18 UTC, JohnyNiks commented on src/components/LineLike/LineLike.tsx
> +    function addLikeOrDislike(set1: any, set2: any, value1: number, value2: boolean): void{
Эта функция вбирает в себя много функционала: она одновременно обрабатывает и лайки и дизлайки. Лучше разделять эти обработки на 2 разные функции

2022-05-11 07:18 UTC, JohnyNiks commented on src/components/Title/Title.scss
> +.post-card-big__name{
Компонент Title должен быть изолированным, то есть в стилях этого компонента не должно быть описания стилей из другого компонента. Они описываются в другом компоненте, а базовые стили для этого компонента должны содержаться здесь и иметь класс .title

2022-05-11 07:18 UTC, JohnyNiks commented on src/components/PostList/PostList.tsx
> +const Posts = ({posts}: Posts) => {
Компонент Posts нужно вынести в отдельный компонент, а не писать в рамках PostList

2022-05-11 07:18 UTC, JohnyNiks commented on src/components/PostCard/postcard.tsx
> +export const PostCard = ({size, postcardName, postcardText, img, className}: PostCardProps) => {
Переименуй имя файла в PostCard.tsx, а не postcard.tsx

2022-05-11 12:22 UTC, DaniilBenyash commented
...

2022-05-11 12:24 UTC, DaniilBenyash commented
PostCard.tsx при коммите, всё ровно переименовывается в нижний регистр

2022-05-15 19:53 UTC, JohnyNiks requested changes

2022-05-15 19:53 UTC, JohnyNiks commented on src/components/LineLike/LineLike.tsx
> +                    <button onClick={() => {addLikeOrDislike(setLikeValue, likeValue)}} className='line-like__button_style'>
Используй уже готовые компоненты Button здесь

2022-05-15 19:53 UTC, JohnyNiks commented on src/components/LineLike/LineLike.tsx
> +                    <button onClick={() => {addLikeOrDislike(setDislikeValue, dislikeValue)}} className='line-like__button_style'>
И здесь

2022-05-15 19:53 UTC, JohnyNiks commented on src/components/LineLike/LineLike.tsx
> +
Так как количество лайков и дизлайков не должно быть ограничено одним. Лучше реализовать функцию следующим образом
```suggestion
    const addLike = () => {
      setLikeValue((previousValue) => previousValue + 1)
    }
     const addDislike = () => {
       setDislikeValue((previousValue) => previousValue + 1)
    }
```
а в кнопки уже установить эти функции
`<button onClick={addLike} …/>`
`<button onClick={addDislike} …/>`

2022-05-15 19:53 UTC, JohnyNiks commented on src/components/Posts/Posts.tsx
> +                if(id === 0){
Тут лучше именовать как есть - через index. Потому что id вносит неразбериху 
```suggestion
            {posts.map((post, index) => {

                if(index === 0){
```

2022-05-24 20:32 UTC, JohnyNiks requested changes

2022-05-24 20:32 UTC, JohnyNiks commented on src/features/posts/usePosts.ts
> +    }
Любой dispatch или вызов другой функции должен быть в рамках хука, а не в самой функции

2022-05-24 20:32 UTC, JohnyNiks commented on src/page/Post/Post.tsx
> +    const { posts, onLikePost, onDislikePost, onFavoritePost } = usePosts()
Запрос за данными и сам хук должны быть вне компонента Post, а в сам компонент должны приходить пропсы вида: title, text, id, image и тд.

2022-05-24 20:32 UTC, JohnyNiks commented on src/page/Post/Post.tsx
> +                <h1 className='post__title'>{posts?.[Number(id)-1].title}</h1>
Исходя из комментария выше здесь и в других свойствах должно быть как-то так
```suggestion
                <h1 className='post__title'>{title}</h1>           
```

2022-05-24 20:32 UTC, JohnyNiks commented on src/page/PostList/components/LineLike/LineLike.tsx
> +    const { posts, onLikePost, onDislikePost, onFavoritePost } = usePosts()
Тоже самое здесь

2022-05-24 20:32 UTC, JohnyNiks commented on tsconfig.json
> +, "page/PostList"  ]
Это здесь лишнее

2022-06-01 18:54 UTC, JohnyNiks requested changes

2022-06-01 18:54 UTC, JohnyNiks commented on src/features/posts/usePosts.ts
> +    })
Обновлять посты тебе нужно на данном этапе только при после первого монтирования компонента, поэтому имеем []. И лучше не сокращать, если это влияет на читаемость кода
```suggestion
    useEffect(() => {
        if (!posts) {
          dispatch(fetchPosts())}
        }
    }, [])
```

2022-06-01 18:54 UTC, JohnyNiks commented on src/page/Post/Post.tsx
> +    const infoPost = getInfoOnePost(Number(id)-1);
Всегда получай информацию о посте по id и не преобразовывай его
```suggestion
    const infoPost = getInfoOnePost(id);
```

2022-06-01 18:54 UTC, JohnyNiks commented on src/page/PostList/components/LineLike/LineLike.tsx
> +    const infoPost = getInfoOnePost(postId-1);
здесь то же самое про id
```suggestion
    const infoPost = getInfoOnePost(postId);
```

2022-06-01 18:54 UTC, JohnyNiks commented on src/page/PostList/components/PostCard/PostCardd.tsx
> +    const { getOnePost } = usePosts();
Компонент PostCard должен принимать функцию как пропс снаружи, а не зависеть от хука `usePosts`.

2022-06-01 18:54 UTC, JohnyNiks commented on src/page/PostList/components/PostCard/PostCardd.tsx
> +    <Link to={`/post/${id}`} onClick={() => getOnePost(id)}><img src={image} alt="" className={className.img}/></Link>
Так как Link - это ссылка, то лучше не навешивать на неё еще и поведение через onClick. А сделать запрос за информацией уже на самой странице на которую ведет ссылка

2022-06-01 18:54 UTC, JohnyNiks commented on src/sagas/getDataSagas.ts
> +        }))
Оборачивать в дополнительный промисс нет необходимости, лучше вынести саму функцию-запрос в отдельную функцию и обработать ошибки там
```suggestion
        const fetchPosts = () => {
          try {
           const response = fetch(`https://studapi.teachmeskills.by/blog/posts/?limit=70&offset=0`)) 
          }
           …
        }
        const data: Data = yield call(fetchPosts)
```

2022-06-08 18:30 UTC, JohnyNiks requested changes

2022-06-08 18:30 UTC, JohnyNiks commented on src/features/filterPosts/filterPostsSlice.ts
> +export type filt = {
Не сокращай названия
```suggestion
export type filteredPosts = {
```

2022-06-08 18:30 UTC, JohnyNiks commented on src/features/filterPosts/filterPostsSlice.ts
> +import { stat } from "fs";
Лишний импорт

2022-06-08 18:30 UTC, JohnyNiks commented on src/features/filterPosts/useFilterPosts.ts
> +    const filPosts = useAppSelector(state => state.filterPosts.posts)
```suggestion
    const filteredPosts = useAppSelector(state => state.filterPosts.posts)
```

2022-06-08 18:30 UTC, JohnyNiks commented on src/page/Post/Post.tsx
> +    const idForInfoPost = Number(id) - 1;
Не отнимай от id никаких чисел, это не index. Поэтому просто используй сам id

2022-06-08 18:30 UTC, JohnyNiks commented on src/sagas/getDataSagas.ts
> +        const response: Response = yield fetch(`https://studapi.teachmeskills.by/blog/posts/?limit=70&offset=0`)
Используй свойства limit и offset из аргументов в fetchPosts (нужно добавить их туда)

2022-06-12 15:02 UTC, JohnyNiks approved these changes

2022-06-16 09:37 UTC, merged